name: C CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_valgrind:
        description: "Run Valgrind?"
        type: boolean
        default: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get install -y build-essential valgrind

    - name: Run Functional Tests
      run: make run_functional_tests


  run-valgrind:
    needs: build_and_test
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_valgrind }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Valgrind
        run: sudo apt-get update && sudo apt-get install -y build-essential valgrind
     
      - name: Run Valgrind Tests
        run: make run_valgrind_tests