name: C CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get install -y build-essential valgrind

    # - name: Install Dependencies
    #   run: sudo apt-get install libcheck-dev  # Example for testing libraries

    - name: Run Functional Tests
      run: make run_functional_tests

    - name: Run Valgrind Tests
      run: make run_valgrind_tests
      continue-on-error: false

    - name: Clean Up
      run: make clean